# Generated by Django 4.0.1 on 2022-01-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='title',
            field=models.CharField(default='GalleryImage', max_length=255),
            preserve_default=False,
        ),
    ]
