# Generated by Django 4.0.1 on 2022-01-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='units',
            field=models.IntegerField(default=0),
        ),
    ]
