# Generated by Django 4.0.1 on 2022-01-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_stock_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='units_sold',
            field=models.IntegerField(default=0),
        ),
    ]
