# Generated by Django 4.0.1 on 2022-02-04 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='product',
        ),
    ]
