# Generated by Django 4.0.1 on 2022-02-04 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_stock_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='product.product'),
        ),
    ]
