# Generated by Django 4.0.1 on 2022-02-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_productquestions_productanswers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='VendorCategory',
            new_name='vendorcategory',
        ),
        migrations.AlterField(
            model_name='vendorcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
