# Generated by Django 4.0.1 on 2022-02-16 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0010_vendor_zipcode'),
        ('product', '0017_rename_vendorcategory_product_vendorcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('ordering', models.IntegerField(default=0)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='vendor.vendor', verbose_name='Subcategory')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendorcategory',
        ),
        migrations.DeleteModel(
            name='VendorCategory',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.subcategory'),
        ),
    ]
