# Generated by Django 4.0.1 on 2022-02-16 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_subcategory_remove_product_vendorcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='vendor',
            new_name='creator',
        ),
    ]
