# Generated by Django 4.0.1 on 2022-02-16 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0010_vendor_zipcode'),
        ('product', '0019_rename_vendor_subcategory_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='creator',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='vendor.vendor', verbose_name='Vendor'),
        ),
    ]
