# Generated by Django 4.0.1 on 2022-01-23 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address_2',
            new_name='address2',
        ),
    ]
