# Generated by Django 4.0.1 on 2022-01-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_address_1_order_address1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='zip_code',
            new_name='zipcode',
        ),
    ]
