# Generated by Django 4.0.1 on 2022-02-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_option',
            field=models.CharField(default='paypal', max_length=10),
            preserve_default=False,
        ),
    ]
