# Generated by Django 4.0.1 on 2022-02-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_pay_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
